package-lock.json, projects/ngx-components-doc/src/app/pages/dialog/components/custom-dialog/constants/custom-dialog-code-ts.constant.ts, projects/ngx-components-doc/src/app/pages/dialog/components/custom-dialog/custom-dialog.component.ts
=> fix dialog doc

projects/applicature/components/README.md
=> Fix doc url

copy-docs.server.js, projects/applicature/components/src/lib/button/button.component.scss, projects/applicature/components/src/lib/button/button.component.ts, projects/applicature/components/src/lib/dropdown-menu/dropdown-menu.component.html, projects/applicature/components/src/lib/dropdown-menu/dropdown-menu.component.scss, projects/applicature/components/src/lib/dropdown-menu/dropdown-menu.component.ts, projects/applicature/components/src/lib/dropdown-menu/interfaces/dropdown-config.interface.ts, projects/applicature/components/src/lib/dropdown-menu/interfaces/dropdown-position-styles.interace.ts, projects/applicature/components/src/lib/network-dropdown/network-dropdown.component.html, projects/applicature/components/src/lib/network-dropdown/network-dropdown.component.scss, projects/applicature/components/src/lib/network-dropdown/network-dropdown.component.ts
Added ability to set dropdown as full width.
=> feat(): add ability to set full width for the dropdown

projects/applicature/components/src/lib/network-dropdown/index.ts, projects/applicature/components/src/lib/network-dropdown/interfaces/index.ts, projects/applicature/components/src/lib/network-dropdown/interfaces/selected-network.interface.ts, projects/applicature/components/src/lib/network-dropdown/network-dropdown.component.ts
added emitted event when selected network;
=> Uc network dropdown evt

projects/applicature/components/src/lib/account-balance/account-balance.component.ts, projects/applicature/components/src/lib/account-button/account-button.component.ts, projects/applicature/components/src/lib/connect-wallet/connect-wallet.component.ts, projects/applicature/components/src/lib/connect/services/wallet-connect/wallet-connect.service.ts, projects/applicature/components/src/lib/faucet/faucet.component.ts, projects/applicature/components/src/lib/modals/account-modal/account-modal.component.ts, projects/applicature/components/src/lib/modals/transfer-modal/transfer-modal.component.ts, projects/applicature/components/src/lib/network-dropdown/network-dropdown.component.ts, projects/applicature/components/src/lib/transactions/services/transaction/transaction.service.ts, projects/applicature/styles/src/lib/scss/abstract/_as-variables.scss, projects/demo/src/app/app.component.ts, projects/ngx-components-doc/src/app/modules/need-wallet-connection/need-wallet-connection.component.ts, projects/ngx-components-doc/src/app/pages/connect-wallet/components/custom-connect-button/constants/custom-connect-button-code-ts.constant.ts, projects/ngx-components-doc/src/app/pages/connect-wallet/components/custom-connect-button/custom-connect-button.component.ts, projects/ngx-components-doc/src/app/pages/transactions-history/components/basic-transaction-history/basic-transaction-history.component.ts, projects/ngx-components-doc/src/app/pages/transactions-history/components/basic-transaction-history/constants/basic-transaction-history-code-ts.constant.ts
=> feat(UC-57): optimize wallet connections

projects/applicature/components/package.json, projects/applicature/components/src/lib/connect/components/connect-modal/connect-modal.component.ts, projects/applicature/components/src/lib/connect/components/connect-modal/interfaces/connect-dialog-data.interface.ts, projects/applicature/components/src/lib/connect/services/wallet-connect/wallet-connect.service.ts, projects/applicature/components/src/lib/interfaces/ethereum.ts, projects/applicature/components/src/test.ts, projects/applicature/styles/package.json, projects/demo/src/polyfills.ts, projects/ngx-components-doc/src/polyfills.ts
=> feat(): fix circular dependency issue

package.json, projects/applicature/ngx-web3-synergy/README.md, projects/applicature/ngx-web3-synergy/package.json, projects/applicature/styles/package.json, projects/ngx-web3-synergy-doc/src/app/components/header/header.component.html
=> Uc 63 rename project

package-lock.json
=> Uc 63 change package lock

.github/workflows/master.yml, projects/ngx-web3-synergy-doc/src/index.html
=> Uc 63 rename title

projects/ngx-web3-synergy-doc/src/index.html
=> feat(UC-63): rename docs title

pull-request-template.md
=> feat(UC-63): add pr readme

.run/build-package_styles.run.xml, .run/build-package_web3-synergy.run.xml, .run/build.run.xml, .run/build_styles.run.xml, .run/build_web3-synergy.run.xml, .run/run.run.xml, .run/run_demo.run.xml, .run/watch_styles.run.xml, .run/watch_web3-synergy.run.xml, package-lock.json, package.json, projects/applicature/ngx-web3-synergy/README.md
=> Uc 63 fix doc

projects/applicature/ngx-web3-synergy/src/lib/button/button.component.spec.ts
=> UC(62): cover button component

projects/applicature/ngx-web3-synergy/README.md
=> fix readme

projects/applicature/ngx-web3-synergy/package.json, projects/applicature/ngx-web3-synergy/src/lib/connect-wallet/connect-wallet.component.html, projects/applicature/ngx-web3-synergy/src/lib/connect-wallet/connect-wallet.component.ts, projects/applicature/ngx-web3-synergy/src/lib/connect/index.ts, projects/applicature/ngx-web3-synergy/src/lib/dropdown-menu/dropdown-menu.component.html, projects/applicature/ngx-web3-synergy/src/lib/overlay/interfaces/overlay-customization-config.interface.ts, projects/ngx-web3-synergy-doc/src/app/pages/connect-wallet/components/basic-connect-wallet/basic-connect-wallet.component.html
=> Uc 68 adapting

.stylelintrc.json, projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.ts, projects/applicature/ngx-web3-synergy/src/lib/account-button/account-button.component.html, projects/applicature/ngx-web3-synergy/src/lib/account-button/account-button.component.scss, projects/applicature/ngx-web3-synergy/src/lib/account-button/account-button.component.ts, projects/applicature/ngx-web3-synergy/src/lib/copy-to-clipboard/copy-to-clipboard.component.scss, projects/applicature/ngx-web3-synergy/src/lib/dropdown-menu/dropdown-menu.component.scss, projects/applicature/ngx-web3-synergy/src/lib/modals/account-modal/account-modal.component.html, projects/applicature/ngx-web3-synergy/src/lib/modals/account-modal/account-modal.component.scss, projects/applicature/ngx-web3-synergy/src/lib/modals/account-modal/account-modal.component.ts, projects/applicature/ngx-web3-synergy/src/lib/transactions/components/transactions-history/transactions-history.component.ts, projects/applicature/ngx-web3-synergy/src/lib/transactions/components/transactions-list/transactions-list.component.scss
=> Uc 68 fix dialogs styles

projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.html, projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.scss, projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.spec.ts, projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.ts, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.scss, projects/applicature/ngx-web3-synergy/src/lib/helpers/helpers.ts, projects/demo/src/app/modules/card/card.component.scss
fixed account balance responsive design
=> feat(UC-68): accound balance responsive

projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.spec.ts, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.scss, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.spec.ts, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.ts, projects/applicature/styles/package.json, projects/applicature/styles/src/lib/colors.ts, projects/applicature/styles/src/lib/scss/abstract/_as-variables.scss, projects/demo/src/app/modules/example-buttons/example-buttons.component.html
=> feat(UC-68): add button disable state

projects/applicature/ngx-web3-synergy/src/lib/connect/services/wallet-connect/wallet-connect.service.spec.ts, projects/applicature/ngx-web3-synergy/src/lib/faucet/faucet.component.html, projects/applicature/ngx-web3-synergy/src/lib/faucet/faucet.component.scss, projects/applicature/ngx-web3-synergy/src/lib/modals/transfer-modal/transfer-modal.component.scss, projects/applicature/ngx-web3-synergy/src/lib/table/table.component.scss
=> feat(UC-68): rework faucet

projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.html, projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.scss, projects/applicature/ngx-web3-synergy/src/lib/account-balance/account-balance.component.ts, projects/demo/src/app/modules/example-account-balance/example-account-balance.component.scss
made account balance responsive
=> Uc 68 account balance responsive

projects/applicature/ngx-web3-synergy/README.md, projects/applicature/ngx-web3-synergy/package.json, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.scss, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.spec.ts, projects/applicature/ngx-web3-synergy/src/lib/button/button.component.ts, projects/applicature/ngx-web3-synergy/src/lib/connect-wallet/connect-wallet.component.scss, projects/applicature/ngx-web3-synergy/src/lib/directives/check-el-width/check-el-width.directive.ts, projects/applicature/ngx-web3-synergy/src/lib/network-dropdown/network-dropdown.component.html, projects/applicature/ngx-web3-synergy/src/lib/network-dropdown/network-dropdown.component.scss, projects/applicature/ngx-web3-synergy/src/lib/network-dropdown/network-dropdown.component.ts
made networks dropdown responsive.
=> feat(UC-68): networks responcive

package-lock.json, projects/applicature/ngx-web3-synergy/src/lib/connect/services/wallet-connect/mocks/wallet-connect-service.mock.ts, projects/applicature/ngx-web3-synergy/src/lib/connect/services/wallet-connect/wallet-connect.service.ts, projects/applicature/ngx-web3-synergy/src/lib/services/index.ts, projects/applicature/ngx-web3-synergy/src/lib/services/local-storage.service.ts, projects/applicature/ngx-web3-synergy/src/lib/transactions/services/transaction/transaction.service.ts, projects/applicature/ngx-web3-synergy/src/public-api.ts
Check local storage on platforms
=> Check local storage on platforms
